/** Declaration file generated by dts-gen */
declare module 'vue-trend-chart'
export const components: {
    TrendChartCurve: {
        computed: {
            paths: any;
            points: any;
        };
        name: string;
        props: {
            activeLineParams: {
                type: any;
            };
            boundary: {
                required: boolean;
                type: any;
            };
            className: {
                type: any;
            };
            data: {
                required: boolean;
                type: any;
            };
            fill: {
                default: boolean;
                type: any;
            };
            maxAmount: {
                required: boolean;
                type: any;
            };
            maxValue: {
                required: boolean;
                type: any;
            };
            minValue: {
                required: boolean;
                type: any;
            };
            showPoints: {
                default: boolean;
                type: any;
            };
            smooth: {
                default: boolean;
                type: any;
            };
            stroke: {
                default: boolean;
                type: any;
            };
        };
        render: any;
    };
    TrendChartGrid: {
        methods: {
            setHorizontalLinesParams: any;
            setVerticalLinesParams: any;
        };
        name: string;
        props: {
            boundary: {
                required: boolean;
                type: any;
            };
            horizontalLines: {
                default: boolean;
                type: any;
            };
            horizontalLinesNumber: {
                default: number;
                type: any;
            };
            verticalLines: {
                default: boolean;
                type: any;
            };
            verticalLinesNumber: {
                default: number;
                type: any;
            };
        };
        render: any;
    };
    TrendChartLabels: {
        data: any;
        methods: {
            setXLabelsParams: any;
            setYLabelsParams: any;
        };
        mounted: any;
        name: string;
        props: {
            boundary: {
                required: boolean;
                type: any;
            };
            maxValue: {
                type: any;
            };
            minValue: {
                type: any;
            };
            xLabels: {
                type: any;
            };
            yLabels: {
                type: any;
            };
            yLabelsTextFormatter: {
                default: any;
                type: any;
            };
        };
        render: any;
    };
};

export const name: string;

export const props: {
    datasets: {
        required: boolean;
        type: any;
    };
    grid: {
        default: any;
        type: any;
    };
    interactive: {
        default: boolean;
        type: any;
    };
    labels: {
        default: any;
        type: any;
    };
    max: {
        type: any;
    };
    min: {
        type: any;
    };
    padding: {
        default: string;
        type: any;
        validator: any;
    };
};

export function data(): any;

export function destroyed(): void;

export function install(Vue: any): void;

export function mounted(): void;

export function render(h: any): any;

export namespace computed {
    function boundary(): any;

    function chartAxesXCoords(): any;

    function chartOverlayParams(): any;

    function paddingObject(): any;

    function params(): any;

}

export namespace methods {
    function fitLabels(): void;

    function getNearestCoordinate(val: any): any;

    function init(): void;

    function mouseMove(e: any): void;

    function mouseOut(): void;

    function onWindowResize(): void;

    function setSize(): void;

}

export namespace watch {
    function activeLine(val: any): void;

    namespace labels {
        const deep: boolean;

        function handler(): void;

    }

}

